version: "3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - app

  mysql:
    container_name: stu-mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "123456"

  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - mysql