spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/stu_db?serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 19
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500



mybatis:
  type-aliases-package: sww.stuinfo.pojo
  mapper-locations: mapper/*.xml


pagehelper:
  helper-dialect: mysql